### ISSUE TITLE
Regarding connection issue between sub-server and client 

### ISSUE THREAD

**Issue by George-martin-c** [muneeb50/Multithreaded-Online-Quiz-System#2]
I followed the instruction as given in the description PDF file. Firstly I compiled main server then three sub-server and finally the client. Then I ran the main server and all the three sub-severs and then the client. Client gets connected with main server; but when it tries to get connect to any of the three sub-servers, the connection fails(ERROR:- Connection failed with sub-server.). Can you please guide me.

**Comment by yashmudgil** [comment]
@muneeb50 can you plz help.. I am also facing same issue as @George-martin-c told

**Comment by yaswanthksas** [comment]
> I followed the instruction as given in the description PDF file. Firstly I compiled main server then three sub-server and finally the client. Then I ran the main server and all the three sub-severs and then the client. Client gets connected with main server; but when it tries to get connect to any of the three sub-servers, the connection fails(ERROR:- Connection failed with sub-server.). Can you please guide me.

bro the code isnot compling please help me

**Comment by yaswanthksas** [comment]
> @muneeb50 can you plz help.. I am also facing same issue as @George-martin-c told

bro does the code have complied. please help me

**Comment by uckamdar59** [comment]
https://github.com/uckamdar59/Multithreaded-Quiz-in-C

Check this link. It's working fine there

**Comment by muneeb50** [comment]
Hi guys, I have updated the files so there should be no compiling issue now.

**Comment by muneeb50** [comment]
@George-martin-c please make sure that following ports are available before running: 2000, 2001, 2010, 2020, 2030.
Let me know if you still have the issues!

**Comment by yaswanthksas** [comment]
muneeb sir, please explain which code editor to use.
please tell me sir
please reply sir

**Comment by yaswanthksas** [comment]
please explain how to compile the code in code editor, sir.
please please.

**Comment by muneeb50** [comment]
@yaswanthksas you can use VS code, netbeans, atom, or any C/C++ supported editor based on your liking.
As for the compiler, you can install GCC or MinGW for C.

Please refer to the [instructions](https://github.com/muneeb50/Multithreaded-Online-Quiz-System#instructions) for commands to compile/run code.
Thanks

**Comment by Jk1091997** [comment]
![Uploading 16392094812698064094721801311766.jpg…]()
Please tell how to clear this error. Also please provide code how to add questions for every subject and evaluation code

**Comment by Jk1091997** [comment]
[IMG-20211211-WA0017](https://user-images.githubusercontent.com/95957438/146210320-7305139b-8efa-4c2e-842f-f6a8eae23259.jpeg)

Please provide solution for this sir
