### ISSUE TITLE
name code editor

### ISSUE THREAD

**Issue by yaswanthksas** [muneeb50/Multithreaded-Online-Quiz-System#3]
sir, which code editor should use sir

**Comment by yaswanthksas** [comment]
sir,please reply sir

**Comment by muneeb50** [comment]
@yaswanthksas that is a very general question as different programmers use different code editors based on their taste. Some are open-source like Eclipse, Netbeans, Visual Studio Code, Atom, etc. Others are paid ones, more specific to limited languages like Visual Studio, IntelliJ Idea, Sublime Text, etc.

Personally I like to use VS Code, Eclipse or IntelliJ Idea. If you are looking for C/C++ specifically then try Visual Studio (paid) or Netbeans. 

Note: Don't confuse code editors with the compilers, if you are looking for compilers for C/C++ use GCC or MinGW.
