### ISSUE TITLE
sir, it is showing fatal error

### ISSUE THREAD

**Issue by yaswanthksas** [muneeb50/Multithreaded-Online-Quiz-System#4]
C:\Users\Admin\Desktop>gcc -std=c11 main_server.c -o main_server
main_server.c:8:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h> //socket
          ^~~~~~~~~~~~~~
compilation terminated.

**Comment by muneeb50** [comment]
@yaswanthksas socket.h is for unix/linux. If you are using windows machine please refer to this [link](https://stackoverflow.com/a/22432941): https://stackoverflow.com/a/22432941

Thanks!!
