### ISSUE TITLE
Connection failed error

### ISSUE THREAD

**Issue by Jk1091997** [muneeb50/Multithreaded-Online-Quiz-System#5]
[IMG-20211211-WA0017](https://user-images.githubusercontent.com/95957438/146211136-9ff9b888-df0f-48c0-87ac-68eac58f6299.jpeg)

Please provide a solution for this sir

**Comment by yaswanthksas** [comment]
Sir, when I run the code.
It is showing no such directory is found

**Comment by muneeb50** [comment]
@Jk1091997 replace `gets` with `fgets` should resolve the warnings. c99 ended `gets` support. 
Check this https://stackoverflow.com/a/34031565
