### ISSUE TITLE
How to add questions? 

### ISSUE THREAD

**Issue by Jk1091997** [muneeb50/Multithreaded-Online-Quiz-System#7]
Sir please tell where and how to add questions please and how grade it

**Comment by muneeb50** [comment]
That logic is up to you. There are any number of ways to extend this code.
For starters, you can create a file containing question and show them to client one by one, and based on client's answer you can either show next question or calculate marks.

**Comment by Jk1091997** [comment]
Sir it will be very helpful if you give a sample example
